apiVersion: v2
name: carbon-footprint
description: A minimal Helm chart for carbon footprint measurement
version: "1.0.0"
appVersion: "1.0.0"
keywords:
  - monitoring
dependencies:
  - name: prometheus
    version: "27.46.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "10.2.0"
    repository: "https://grafana.github.io/helm-charts"
sources:
  - https://github.com/eumel8/carbon-footprint
  - https://github.com/caas-team/caas-carbon-footprint
maintainers:
  - name: eumel8
    email: f.kloeker@telekom.de
    url: https://www.telekom.com
